In [21]:
import datetime as dt
import pandas as pd 
from dotenv import load_dotenv
from os import getenv

from loader_microservices import MicroServiceLoader

load_dotenv('envar.env')
load_dotenv('stored_procedures.env')

True

In [5]:
credentials_calendario = {"DRIVER": getenv('DRIVER'), "USER": getenv('CALUSER'), "PWD": getenv('CALPWD'), "SERVER": getenv('CALSERVER'),  "DB": getenv('CALDB') }
credentials_productivity = {"DRIVER": getenv('DRIVER'), "USER": getenv('PRODUSER'), "PWD": getenv('PRODPWD'), "SERVER": getenv('PRODSERVER'),  "DB": getenv('PRODDB') }
credentials_smartfactory = {"DRIVER": getenv('DRIVER'), "USER": getenv('SFUSER'), "PWD": getenv('SFPWD'), "SERVER": getenv('SFSERVER'),  "DB": getenv('SFDB') }
        
loader_calendario = MicroServiceLoader(credentials_calendario)
loader_productivity = MicroServiceLoader(credentials_productivity)
loader_smartfactory = MicroServiceLoader(credentials_smartfactory)
        
loader_microservice = MicroServiceLoader()

In [17]:
df_calendario = loader_calendario.descargar_datos(getenv('QUERYCALENDARIO'))
df_costos_consumo = loader_productivity.descargar_datos(getenv('QUERYCOSTOCONSUMOS'))

In [20]:
df_control_costos = pd.merge(df_calendario[~df_calendario['LlegoAlmacen']], df_costos_consumo, on='Orden', how='left')
df_control_costos = df_control_costos.sort_values(by='RelacionSobrecosto', ascending=False)
df_control_costos

,Orden,Cliente,Mercado,ZFER,Vehiculo,CodTipoPieza,Puestodetrabajo,KeyModel,FechaRegistro,HorasQuietas,LlegoAlmacen,CostoPlan,CostoReal,RelacionSobrecosto
384,10971033,"BLINTECH, SOCIEDAD ANONIMA",CentroAmerica,700159583,LAND ROVER RANGE ROVER SPORT 4D UTILITY,0,12P_ENSA,PREENSA,2024-07-15 09:37:37,1,False,244.62747,877.55,3.59
1270,10973290,"BLINTECH, SOCIEDAD ANONIMA",CentroAmerica,700158795,TOYOTA TUNDRA 4D PICK UP,1,18INSFIN,PREEMPQ,2024-07-14 04:34:57,30,False,99.67761,311.36,3.12
381,10968531,CENTUR PRIVATE SECURITY SERVICES,Mexico,700133664,JEEP GRAND CHEROKEE 4D UTILITY,0,01CORTE,04VP03,2024-07-15 06:12:48,4,False,303.95721,876.41,2.88
378,10968598,NORTH GLASS CORPORATION,Japón,700071725,NORTH GLASS JMSDF SHIP SHIP GLASS,41,18INSFIN,SALBAKE,2024-07-15 08:22:18,2,False,182.36767,520.87,2.86
416,10973571,CENTUR PRIVATE SECURITY SERVICES,Mexico,700160239,BMW X1 4D UTILITY,0,15EMBOL,DESAIRE,2024-07-15 07:44:50,3,False,267.22002,740.58,2.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2289,10982544,EPEL,Mexico,700044342,FORD EXPLORER 4D UTILITY,9,Planeacion,Planeacion,NaT,0,False,NaN,NaN,NaN
2290,10982545,EPEL,Mexico,700044342,FORD EXPLORER 4D UTILITY,9,Planeacion,Planeacion,NaT,0,False,NaN,NaN,NaN
2291,10982646,PROTELIFE,Mexico,700133614,BMW X5 4D UTILITY,25,Planeacion,Planeacion,NaT,0,False,NaN,NaN,NaN
2292,10982647,PROTELIFE,Mexico,700133614,BMW X5 4D UTILITY,25,Planeacion,Planeacion,NaT,0,False,NaN,NaN,NaN
2302,10982567,PROTELIFE,Mexico,700159632,FORD EXPLORER 4D UTILITY,90,Planeacion,Planeacion,NaT,0,False,NaN,NaN,NaN

In [27]:
test = pd.DataFrame([{'update_time': dt.datetime.now()}])
test.iloc[0]['update_time']

Timestamp('2024-07-15 11:15:08.519020')